# See options at https://github.com/coogie/oscailte
# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://home-assistant.io
title: Home Assistant
subtitle: Open-source home automation platform running on Python 3
author: Home Assistant
simple_search: https://www.google.com/search
description: Home Assistant is an open-source home automation platform running on Python 3.

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: /blog/:year/:month/:day/:title/
source: source
destination: public/
plugins_dir: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: kramdown
timezone: UTC

# highlighter: coderay

kramdown:
  input: GFM
  auto_ids:       false
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  parse_block_html: true

highlighter: rouge

gems:
  - jekyll-time-to-read
  - octopress-filters
  - octopress-include-tag

paginate: 10          # Posts per page on the blog index
paginate_path: "blog/posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

titlecase: true       # Converts page and post titles to titlecase

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

collections:
  components:
    output: true
  cookbook:
    output: true
  ecosystem:
    output: true
  details:
    output: true
  topics:
    output: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: balloob
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: standard

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: +PaulusSchoutsen
googleplus_hidden: true

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: home-assistant
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-57927901-1

# Facebook Like
facebook_like: true

social:
  visible: false
  facebook:
    app_id: 338291289691179

  twitter:
    account: home_assistant

current_major_version: 0
current_minor_version: 31
current_patch_version: 1
